apiVersion: v1
kind: ConfigMap
metadata:
  name: e2e-test-config
  namespace: local-setup
data:
  bitcoin-electrum-host: "electrumx.local-setup.svc.cluster.local"
  bitcoin-electrum-port: "50003"
  bitcoin-network: "regtest"
  ethereum-node: "ws://geth.local-setup.svc.cluster.local:8546"
  lot-size-satoshis: "1000000"
