= KEEP & tBTC local setup

== Setting up development environment
If you’re on macOS, install Homebrew and https://github.com/keep-network/keep-core/blob/master/scripts/macos-setup.sh[macos-setup.sh] script to setup all necessary tools.

If you are not on macOS or you don't have Homebrew, you need to install:

- Go compiler, at least 1.14
- Geth (Ethereum client), at least 1.9.12
- Solidity, at least 0.5.17
- Truffle, at least 5.1.18
- Protobuf compiler, at least 3.11.4
- `protoc-gen-gogoslick` toolchain
- `jq`

Regardless you use `macos-setup.sh` or not, you should also install:

- https://github.com/pyenv/pyenv[pyenv], at least 1.2.18
- https://github.com/pypa/pipenv[pipenv], at least 2018.11.26


== Installing the system
. Initialize local `geth` using:
+
```
./initialize-geth.sh
```
+
You can skip this step if your local geth is already initialized. This script clears all Ethereum client data, initilizes genesis block, and funds five accounts. All client data are kept in the working directory of this project so all the data used for other projects stay untouched.

. Run local `geth` node using:
+
```
./run-geth.sh
```
. Run Keep & tBTC installation script:
+
```
./install.sh
```
+ 
This script will fetch `keep-core`, `keep-ecdsa`, and `tbtc` source code, deploy contracts of `keep-core`, `keep-ecdsa`, and `tbtc`. It will also build `keep-core` and `keep-ecdsa` off-chain clients.
+
Later on, if you decide to update `tbtc`, you can run just `install-tbtc.sh`. 
+
Keep in mind, `tbtc` depends on `keep-ecdsa` and `keep-ecdsa` depends on `keep-core` so if you decide to update `keep-ecdsa`, you can run `install-keep-ecdsa.sh` followed by `install-tbtc.sh`. 
+
If you decide to update `keep-core`, you have to run `install-keep-core.sh` followed by `install-keep-ecdsa.sh` followed by `install-tbtc.sh` or just the entire `install.sh` again.

== Run clients
The above installation script will configure:

- 1 `keep-core` client
- 3 `keep-ecdsa` clients

To run the `keep-core` client use:
```
./run-core-1.sh
```
+
It is enough to run one `keep-core` client to generate a group and produce relay entries. Setting up more than one client locally is possible but consumes more resources.


To run `keep-ecdsa` clients use:
```
./run-ecdsa-1.sh
```
```
./run-ecdsa-2.sh
```
```
./run-ecdsa-3.sh
```
+ 
There are at least 3 `keep-ecdsa` clients needed to open a keep. Setting up more than three clients locally is possible but consumes more resources.

== Beacon genesis

Before the beacon is able to produce a first relay entry, genesis needs to happen. Genesis triggers the first random beacon group selection.

Genesis should be triggered after `keep-core` client started with:
```
cd keep-core
KEEP_ETHEREUM_PASSWORD="password" ./keep-core --config configs/config.local.1.toml relay genesis
```

Bonded ECDSA keep factory from `keep-ecdsa` contracts requests for new relay entry to reseed after each signer selection but it is also possible to request for a new relay entry manually with:
```
cd keep-core
KEEP_ETHEREUM_PASSWORD="password" ./keep-core --config configs/config.local.1.toml relay request
```

= How to interact with the system

== tBTC dApp

WORK IN PROGRESS
