apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keep-client-{{ .clientIndex }}
  namespace: local-setup
  labels:
    app: keep-client
    type: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keep-client
      type: local
      id: '{{ .clientIndex }}'
  serviceName: keep-client-{{ .clientIndex }}
  volumeClaimTemplates:
  - metadata:
      name: keep-client-data
    spec:
      accessModes: [ReadWriteOnce]
      resources:
        requests:
          storage: 16Mi
  - metadata:
      name: keep-client-config
    spec:
      accessModes: [ReadWriteOnce]
      resources:
        requests:
          storage: 5Mi
  template:
    metadata:
      labels:
        app: keep-client
        type: local
        id: '{{ .clientIndex }}'
    spec:
      containers:
      - name: keep-client-{{ .clientIndex }}
        image: gcr.io/keep-dev-fe24/keep-client
        imagePullPolicy: Always
        ports:
          - containerPort: 3919
        env:
          - name: KEEP_ETHEREUM_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: geth-config
                key: password.txt
          - name: LOG_LEVEL
            value: "debug"
          - name: IPFS_LOGGING_FMT
            value: "nocolor"
        volumeMounts:
          - name: keep-client-config
            mountPath: /mnt/keep-client/config
          - name: keep-client-data
            mountPath: /mnt/keep-client/data
          - name: account-keyfile
            mountPath: /mnt/keep-client/keyfile
        command: ["keep-client", "-config", "/mnt/keep-client/config/keep-client-config.toml", "start"]
      volumes:
      - name: keep-client-config
        persistentVolumeClaim:
          claimName: keep-client-config
      - name: keep-client-data
        persistentVolumeClaim:
          claimName: keep-client-data
      - name: account-keyfile
        configMap:
          name: accounts-keyfiles
          items:
            - key: keyfile-{{ .clientIndex }}
              path: keyfile-{{ .clientIndex }}
      initContainers:
      - name: initcontainer-provision-keep-client
        image: gcr.io/keep-dev-fe24/initcontainer-provision-keep-client-local
        imagePullPolicy: Always
        env:
          - name: ETH_RPC_URL
            value: "http://geth.local-setup.svc.cluster.local:8545"
          - name: ETH_WS_URL
            value: "ws://geth.local-setup.svc.cluster.local:8546"
          - name: ETH_NETWORK_ID
            value: "1101"
          - name: CONTRACT_OWNER_ETH_ACCOUNT_ADDRESS
            value: "{{ .owner.Address }}"
          - name: CONTRACT_OWNER_ETH_ACCOUNT_PRIVATE_KEY
            value: "{{ .owner.PrivateKey }}"
          - name: KEEP_CLIENT_ETH_KEYFILE_PATH
            value: "/mnt/keep-client/keyfile/keyfile-{{ .clientIndex }}"
          - name: KEEP_CLIENT_PEERS
            value: "/dns4/keep-client-0.local-setup.svc.cluster.local/tcp/3919/ipfs/{{ .bootstrapID }}"
          - name: KEEP_CLIENT_ANNOUNCED_ADDRESSES
            value: "/dns4/keep-client-{{ .clientIndex }}.local-setup.svc.cluster.local/tcp/3919"
          - name: KEEP_CLIENT_PORT
            value: "3919"
          - name: KEEP_CLIENT_DATA_DIR
            value: "/mnt/keep-client/data"
        volumeMounts:
          - name: keep-client-config
            mountPath: /mnt/keep-client/config
          - name: account-keyfile
            mountPath: /mnt/keep-client/keyfile
        command: ["node", "/tmp/provision-keep-client.js"]