def total_cpus
  require 'etc'
  Etc.nprocessors
end

# Install vagrant-disksize to allow resizing the vagrant box disk.
unless Vagrant.has_plugin?("vagrant-disksize")
    raise Vagrant::Errors::VagrantError.new, "vagrant-disksize plugin is missing. Please install it using 'vagrant plugin install vagrant-disksize' and rerun the command"
end

Vagrant.configure("2") do |config|
  config.vm.box = "local-setup"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.disksize.size = '15GB'

  config.vm.provider "virtualbox" do |v|
    v.name = "local-setup-vm"
    v.memory = "4096"
    v.cpus = total_cpus - 2
    v.customize ["modifyvm", :id, "--vram", "256"]
  end

  config.vm.provision "shell", path: "./provisioning/clone-repository.sh", privileged: false
  config.vm.provision "shell", path: "./provisioning/update-repository.sh", privileged: false
  config.vm.provision "shell", path: "./provisioning/initialize-geth.sh", privileged: false
  config.vm.provision "shell", path: "./provisioning/run-geth.sh", privileged: false, run: "always"
  config.vm.provision "shell", path: "./provisioning/run-bitcoin.sh", privileged: false, run: "always"
  config.vm.provision "shell", path: "./provisioning/run-install.sh", privileged: false
  config.vm.provision "shell", path: "./provisioning/run-clients.sh", privileged: false, run: "always"
end