apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bitcoind
  namespace: local-setup
spec:
  replicas: 1
  serviceName: bitcoind
  selector:
    matchLabels:
      app: bitcoind
      type: local
  template:
    metadata:
      labels:
        app: bitcoind
        type: local
    spec:
      containers:
        - name: bitcoind
          image: gcr.io/keep-dev-fe24/bitcoind-local
          ports:
            - containerPort: 18332

