apiVersion: v1
kind: Service
metadata:
  name: electrumx
  namespace: local-setup
  labels:
    app: electrumx
    type: local
spec:
  ports:
    - port: 50001
      targetPort: 50001
      name: tcp-50001
    - port: 50002
      targetPort: 50002
      name: tcp-50002
    - port: 50003
      targetPort: 50003
      name: tcp-50003
    - port: 50004
      targetPort: 50004
      name: tcp-50004
    - port: 8000
      targetPort: 8000
      name: tcp-8000
  selector:
    app: electrumx
    type: local