name: E2E tests / Testnet

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  e2e-testnet-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./e2e
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: "npm"
          cache-dependency-path: e2e/package-lock.json

      # We need this step because the `@keep-network/tbtc.js` which we update in
      # next step has an indirect dependency to `@summa-tx/relay-sol@2.0.2`
      # package, which downloads one of its sub-dependencies via unathenticated
      # `git://` protocol. That protocol is no longer supported. Thanks to this
      # step `https://` is used instead of `git://`.
      - name: Configure git to don't use unauthenticated protocol
        run: git config --global url."https://".insteadOf git://

      - run: npm install --save-exact @keep-network/tbtc.js@ropsten

      - name: Run e2e tests
        run: |
          ./e2e-test.js \
            --bitcoin-electrum-host=${{ secrets.KEEP_TEST_ELECTRUMX_HOSTNAME }} \
            --bitcoin-electrum-port=${{ secrets.KEEP_TEST_ELECTRUMX_PORT }} \
            --bitcoin-network="testnet" \
            --bitcoin-depositor-pk=${{ secrets.KEEP_TEST_BTC_DEPOSITOR_PK }} \
            --ethereum-node=${{ secrets.KEEP_TEST_ETH_HOSTNAME_WS }} \
            --lot-size-satoshis="10000"
