name: E2E tests / Locally

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: Install common tools
        working-directory: ./deployments/local-setup-environment/provisioning/
        run: ./install-commons.sh

      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-solidity-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Set up Go environment variables
        run: |
          echo "GOPATH=$HOME/go" >> $GITHUB_ENV
          echo "$HOME/go/bin" >> $GITHUB_PATH
         
      - name: Install Geth
        working-directory: ./deployments/local-setup-environment/provisioning/
        run: ./install-geth.sh

      - name: Install Solidity
        working-directory: ./deployments/local-setup-environment/provisioning/
        run: ./install-solidity.sh

      - name: Install Protobuf
        working-directory: ./deployments/local-setup-environment/provisioning/
        run: ./install-protobuf.sh

      - name: Initialize and run Geth
        run: |
          ./initialize-geth.sh
          ./run-geth.sh &

      - name: Initialize and run Bitcoin Core and ElectrumX
        run: |
          ./initialize-bitcoin.sh
          ./run-bitcoin.sh &

      - name: Run pre-install script
        run: ./pre-install.sh

      - name: Run install script
        run: |
          export E2E_TEST=true
          ./install.sh

      - name: Run Core and ECDSA clients
        run: |
          ./run-core-1.sh &
          ./run-ecdsa-1.sh &
          ./run-ecdsa-2.sh &
          ./run-ecdsa-3.sh &

      - name: Use Node.js 14.17.0
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'

      - name: Prepare environment for running E2E test scripts
        run: ./install-e2e-test.sh

      - name: Run E2E test scripts
        run: ./run-e2e-test.sh
