name: E2E tests / Testnet

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  e2e-testnet-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./e2e
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: "npm"
          cache-dependency-path: e2e/package-lock.json

      - run: npm install --save-exact @keep-network/tbtc.js@ropsten

      - name: Run e2e tests
        run: |
          ./e2e-test.js \
            --bitcoin-electrum-host=${{ secrets.KEEP_TEST_ELECTRUMX_HOSTNAME }} \
            --bitcoin-electrum-port=${{ secrets.KEEP_TEST_ELECTRUMX_PORT }} \
            --bitcoin-network="testnet" \
            --bitcoin-depositor-pk=${{ secrets.KEEP_TEST_BTC_DEPOSITOR_PK }} \
            --ethereum-node=${{ secrets.KEEP_TEST_ETH_HOSTNAME_WS }} \
            --lot-size-satoshis="10000"
