name: E2E tests / Locally

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: Install common tools
        working-directory: ./deployments/local-setup-environment/provisioning/
        run: ./install-commons.sh

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Set up Go environment variables
        run: |
          echo "GOPATH=$HOME/go" >> $GITHUB_ENV
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Install Geth
        working-directory: ./deployments/local-setup-environment/provisioning/
        run: ./install-geth.sh

      - name: Install Solidity
        working-directory: ./deployments/local-setup-environment/provisioning/
        run: ./install-solidity.sh

      - name: Install Protobuf
        working-directory: ./deployments/local-setup-environment/provisioning/
        run: ./install-protobuf.sh

      - name: Initialize and run Geth
        run: |
          ./initialize-geth.sh
          ./run-geth.sh &

      - name: Initialize and run Bitcoin Core and ElectrumX
        run: |
          ./initialize-bitcoin.sh
          ./run-bitcoin.sh &

      - name: Run pre-install script
        run: ./pre-install.sh

      - name: Run install script
        run: |
          export E2E_TEST=true
          ./install.sh

      - name: Run Core and ECDSA clients
        run: |
          ./run-core-1.sh &
          ./run-ecdsa-1.sh &
          ./run-ecdsa-2.sh &
          ./run-ecdsa-3.sh &

      # We need this step because the `@keep-network/tbtc.js` which we update in
      # next step has an indirect dependency to `@summa-tx/relay-sol@2.0.2`
      # package, which downloads one of its sub-dependencies via unathenticated
      # `git://` protocol. That protocol is no longer supported. Thanks to this
      # step `https://` is used instead of `git://`.
      - name: Configure git to don't use unauthenticated protocol
        run: git config --global url."https://".insteadOf git://

      - name: Prepare environment for running E2E test scripts
        run: ./install-e2e-test.sh

      - name: Run E2E test scripts
        run: ./run-e2e-test.sh
