name: Code Format Checks

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  code-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: yarn install

      - name: Check formatting
        run: yarn run format
